version: '3.8'

services:

  warehouse-service:
    image: warehouse-service:1.0.0
    container_name: warehouse-service
    networks:
    - inventium
    ports:
      - "7450:7450"
    env_file:
      - app.env
    volumes:
      - ./logs:/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7450/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  inventium:
    name: inventium
    external: true
